name: Portfolio CI

on:
  schedule:
    - cron: '0 */3 * * *'   # Runs every 3 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pick random commit message
        run: |
          COMMIT_MESSAGE=$(shuf -n 1 syslog.txt)
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          echo "### ⏱ Last Updated: $(date '+%Y-%m-%d %H:%M:%S')" > temp.md
          echo "" >> temp.md
          cat README.md >> temp.md
          mv temp.md README.md

      - name: Configure git
        run: |
          git config user.name "chandrakantteotia"
          git config user.email "chandrakantteotia@gmail.com"

      - name: Commit changes
        run: |
          git add README.md
          git commit -m "${{ env.COMMIT_MESSAGE }} - $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push
